### ISSUE TITLE
Toolbar: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by ishansasika** [ticruz38/svelte-sheets#3]
![image](https://user-images.githubusercontent.com/48113397/142864630-fc3873b7-4240-45d3-ba39-c1b13c5f5961.png)
![image](https://user-images.githubusercontent.com/48113397/142864680-9fd7e3f6-e4a5-4b40-9537-b905f91342e5.png)

I am getting this error when try to get started with svelte-sheets package. Can you help me with that ?

**Comment by ticruz38** [comment]
been packaging the lib differently, can you give it another try with svelte-sheets@1.0.0?
