### ISSUE TITLE
SvelteKit integration?

### ISSUE THREAD

**Issue by Gildedter** [ticruz38/svelte-sheets#4]
Will this work out of the box with sveltekit?

**Comment by MarcDAFrame** [comment]
wondering this aswell

**Comment by ticruz38** [comment]
https://kit.svelte.dev/docs/packaging

**Comment by ticruz38** [comment]
would need to be packaged using that utility

**Comment by ticruz38** [comment]
Super busy at the moment, I'm happy to welcome pull request

**Comment by ticruz38** [comment]
just pushed version 1.0.0, I can confirm it works with svelte-kit 🎊

**Comment by MarcDAFrame** [comment]
Sweet good stuff @ticruz38 

Unfortunately finished the project I was going to use it on, but will 100% use this in the future. Thanks for the hardwork!

**Comment by ticruz38** [comment]
This is arguably the best in browser cheatsheet... spread the words :D ! 
there is a few more features that would need to be shipped though.
