### ISSUE TITLE
Running on Sveltekit: FileReader is not defined

### ISSUE THREAD

**Issue by ghost** [ticruz38/svelte-sheets#5]
Hi, 

First of all, Thanks for all of the great work you are doing!

Still a noob in svelte & sveltekit, when I try to use this library I got, 

```
FileReader is not defined
ReferenceError: FileReader is not defined
    at eval (/node_modules/svelte-sheets/Toolbar.svelte:28:2)
```
    
Though works fine with,
`import { Sheet } from 'svelte-sheets';`

Toolbar giving me this error!

Anything wrong with how I'm packaging this library with Sveltekit?

**Comment by ticruz38** [comment]
This is probably an SSR incompatibility, the code is run on the server, and FileReader is not defined here.
you should try to use a shim
